spring:
  application:
    name: api-gateway
#  config:
#    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          lowerCaseServiceId: true
#          enabled: true

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka